version: "3"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
        - redis_data:/data
    ports:
        - "6379:6379"
    restart: always
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 1s
        timeout: 1s
        retries: 3
    env_file:
      - .env

volumes:
    redis_data: