version: "3.8"
services:
  redis:
    image: "redis:alpine"
    container_name: "shortener-redis"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 3
    env_file:
      - .env

  shortener:
    build:
      context: .
      dockerfile: Dockerfile
      target: shortener
    container_name: "shortener"
    ports:
      - "8080:${PORT}"
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data: