openapi: '3.0.0'
info:
  title: URL Shortener API
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /encode:
    post:
      summary: Shorten URL
      description: This endpoint is used to shorten a given URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EncodeRequest'
      responses:
        '201':
          description: URL successfully shortened.
          content:
            text/plain:
              example: "co8j2j1ggvkc73enu60g"
              schema:
                type: string
        '400':
          description: Invalid request body or URL.
        '500':
          description: Internal server error.
  /decode:
    get:
      summary: Redirect
      description: This endpoint is used to redirect to the original URL from the shortened URL.
      parameters:
        - in: query
          name: short
          schema:
            type: string
          required: true
          description: The shortened URL.
      responses:
        '302':
          description: Redirect to the original URL.
        '400':
          description: Short query param is required.
        '404':
          description: Not found.
        '500':
          description: Internal server error.
components:
  schemas:
    EncodeRequest:
      type: object
      properties:
        url:
          type: string
          description: The URL to be shortened.
      required:
        - url